# Cloudflare Pages configuration
name = "score-quiz"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]
main = "./functions/_worker.js"

# Static site settings
[site]
bucket = "./dist"

# Specify environment bindings that will be available to your functions
[vars]
API_KEY = "example_key_for_dev"

# KV Namespace binding
[[kv_namespaces]]
binding = "SCORES_KV"
id = "your-kv-id-here"
preview_id = "your-preview-kv-id-here"

# D1 Database binding (if needed)
[[d1_databases]]
binding = "DB"
database_name = "score_database"
database_id = "your-d1-id-here"

# Example environment-specific settings
[env.production]
[env.production.vars]
ENVIRONMENT = "production"

[env.staging]
[env.staging.vars]
ENVIRONMENT = "staging" 